# Generated by Django 4.0 on 2021-12-23 03:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_goodscategory_parent_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodscategory',
            name='parent_category',
            field=models.ForeignKey(blank=True, help_text='父目录', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_cat', to='goods.goodscategory', verbose_name='父类目级别'),
        ),
    ]
